### ISSUE TITLE
Excluding an url rather than a domain

### ISSUE THREAD

**Issue by nsa** [hexojs/hexo-filter-nofollow#12]
I wonder if it is feasible to exclude an url rather than a whole domain. For example, I would like to exclude my twitter profile but I don't want to exclude whole twitter profiles.

Maybe an option like `exclude_url` could be implemented for this.
```yaml
nofollow:
  enable: true
  field: site
  exclude:
    - 'exclude1.com'
    - 'exclude2.com'
  exclude_url:
    - 'twitter.com/myprofile'
```
